/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syj_faceremover_FaceRemover */

#ifndef _Included_com_syj_faceremover_FaceRemover
#define _Included_com_syj_faceremover_FaceRemover
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syj_faceremover_FaceRemover
 * Method:    DectectFace
 * Signature: (J)Lcom/syj/faceremover/FaceRemover/FaceResults;
 */
JNIEXPORT jobject JNICALL Java_com_syj_faceremover_FaceRemover_DectectFace
  (JNIEnv *, jobject thiz, jlong);

JNIEXPORT jobject JNICALL Java_com_syj_faceremover_FaceRemover_DectectFace2
        (JNIEnv *, jobject thiz, jbyteArray image, jint width,jint height,jint channel);

JNIEXPORT jboolean JNICALL
Java_com_syj_faceremover_FaceRemover_EngingInit(JNIEnv *env, jobject thiz);



#ifdef __cplusplus
}
#endif
#endif
